config/routes.rb
Rails.application.routes.draw do
  get    "sessions/new"

	root   "pages#main"
	get    "/signup",         to: "users#new"	 
	get    "/login",          to: "sessions#new"
	post   "/login",          to: "sessions#create"
	delete "/logout",         to: "sessions#destroy"
	post   "/users/:id/edit",	to: "users#edit"
	post   "/rewards/new",    to: "admin/rewards#create"
	patch  "/rewards/:id",    to: "rewards#purchase"

	resources :admin, only: [:index]
	resources :users
	resources :rewards, only: [:index, :new, :edit]
	
	namespace :admin do 
		resources :users, only: [:index,:create, :destroy, :edit]
		resources :rewards
	end 
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reward.rb
class Reward < ApplicationRecord
	has_many :user_rewards
	has_many :users, through: :user_rewards
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: true, length: {maximum:50}
	validates :email, presence: true, length: {maximum:250}, uniqueness: true
	validates :password, presence: true, length: {minimum: 6}

	has_many :user_rewards
	has_many :rewards, through: :user_rewards
	has_secure_password

	enum role: ["default", "admin"]

	def add_points(points)
		self.available_points += points
	end

	def spend_points(points)
		self.update_attribute(:available_points, (self.available_points - points)) 
		self.update_attribute(:spent_points, (self.spent_points + points))
	end 

	def rewards
		return nil if self.user_rewards.nil?
		user_rewards = self.user_rewards
		user_rewards.map do |user_reward|
			Reward.find(user_reward.reward_id)
		end 
	end 
end

app/models/user_reward.rb
class UserReward < ApplicationRecord
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	def require_admin
		render file: "/public/404" unless current_admin?
	end 	
end 

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  before_action :require_admin

	def new
		@reward = Reward.new
	end 

	def create
		@reward = Reward.create(reward_params)
		redirect_to admin_rewards_path
	end 

	def edit
		@reward = Reward.find(params[:id])
	end 

	def update
		@reward = Reward.find(params[:id])
		@reward.update(reward_params)
		redirect_to admin_rewards_path
	end 

	def index
		@rewards = Reward.all
	end 

	def destroy
		Reward.find(params[:id]).destroy
		redirect_to admin_rewards_path
	end 
	
	private 

	def reward_params
		params.require(:reward).permit(:name,:description, :price)
	end 
end 

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	before_action :require_admin
	def index
		@users = User.all
	end 

	def edit
		@user = User.find(params[:id])
	end 

	def update
		user = User.find(params[:id])
		user.update(user_params)
		byebug
		redirect_to admin_users_path
	end 

	def destroy
		user = User.find(params[:id])
		user.destroy

		redirect_to admin_users_path
	end 

	def require_admin
		render file: "/public/404" unless current_admin?
	end 

	private 

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end 

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	
	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end 

	def current_admin?
		current_user && current_user.admin?
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def main
    render :main
  end 

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
	def index
		@rewards = Reward.all
	end 

	def edit 
		user = User.find(session[:user_id])
		reward = Reward.find(params[:id])
		user.user_rewards.create(reward_id: reward.id)
		user.spend_points(reward.price)		
		redirect_to rewards_path
	end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			if user.role == "admin"
				redirect_to admin_users_path(user)
			else  
				redirect_to user_path(user)
			end 
		else 
			render :new
		end 
	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		@user = User.find(params[:id])
		if session[:user_id] == @user.id
			render :show	
		else 
			render file:'/public/401.html'
		end 
	end 
	
	def new
		@user = User.new
	end 

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to "/login"
		else 
			render :new
		end 
	end 
	
	def edit
		@user = User.find(params[:id])
		@user.update_attribute(:available_points, params[:user][:available_points])
		redirect_to admin_users_path
	end 

	def update
		user = User.find(params[:id])
		user.update(user_params)
		redirect_to admin_users_path
	end 

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/rewards/_admin-nav-bar.html.erb
<div class="topnav">
    <%= link_to "All users", admin_users_path %>
    <%= link_to "Rewards", admin_rewards_path %>
</div>

app/views/admin/rewards/_form.html.erb
<div class="form">
	<%= form_tag(new_reward_path, class: "form") do %>
		<%=text_field_tag "reward[name]"%>
		<%=text_field_tag "reward[description]"%>
		<%=text_field_tag "reward[price]"%>
		<%=submit_tag(value = "Create Reward")%>
	<%end%>
</div>

app/views/admin/rewards/edit.html.erb
<%= render partial: "admin-nav-bar"%>

<%= form_for [:admin, @reward], :html=> {class: 'form' } do |f| %>
	<%= f.label      :name %>
	<%= f.text_field :name %>

	<%= f.label      :description%>
	<%= f.text_field :description%>

	<%= f.label      :price%>
	<%= f.text_field :price%>
	<%=f.submit %>

<%end%>

app/views/admin/rewards/edit_html.erb
<%= form_for [:admin, @reward] do |f| %>
	<%= f.label      :name %>
	<%= f.text_field :name %>

	<%= f.label      :description%>
	<%= f.text_field :description%>

	<%= f.label      :price%>
	<%= f.text_field :price%>
	<%=f.submit %>

<%end%>

app/views/admin/rewards/index.html.erb
<%= render partial: "admin-nav-bar"%>
<p class="form"><%=link_to "Create Reward", new_admin_reward_path %></p>
<h1>Available Rewards:</h1>
<div class="form">
  <% @rewards.each do |reward| %>
  <div class="boxed">
    <p>Name: <%=reward.name%></p>
    <p>Description: <%=reward.description%></p>
    <p>Price: <%=reward.price%></p>
    <%= link_to "Edit", edit_admin_reward_path(reward) %>
    <%= link_to "Delete", admin_reward_path(reward), method: "delete" %>
  </div>
    <% end %>
  </form>
</div>

app/views/admin/rewards/new.html.erb
<%= render partial: "admin-nav-bar"%>

<h1>Create a New Reward:</h1>
<%= render partial: "form" %>

app/views/admin/users/_admin-nav-bar.html.erb
<div class="topnav">
    <%= link_to "All users", admin_users_path %>
    <a href="/login">Log In</a>
    <a href="/rewards">Rewards</a>
</div>

app/views/admin/users/_edit.html.erb
<%=form_tag(edit_user_path(user), {method: :get, class: "form"}) do %>
	<%=text_field_tag 'user[available_points]'%>
	<%=submit_tag(value = "Add Points")%>
<%end%>

app/views/admin/users/edit.html.erb
<%= render partial: "admin-nav-bar"%>

<h3> username, email, password </h3>
<%=form_tag(user_path(@user), {method: :put, class: "form"}) do %>
	<%=text_field_tag 'user[username]'%>
  <%=text_field_tag 'user[email]'%>
	<%=submit_tag(value = "Edit User")%>
<%end%>

app/views/admin/users/index.html.erb
<%= render partial: "admin-nav-bar"%>
<div class="container">
<h1>All Users</h1>

<% @users.each do |user|%>
		<div class="items">
		<h2><%=user.username%></h2>
		<p> <%=user.email %></p>
		<p><%=user.available_points%></p>
		
		<p>Set New Point Total:</p>
		<%=render partial: 'edit', locals: {user: user}%> 
		<%=link_to "Edit", edit_admin_user_path(user) %>
		<%=link_to "Delete", admin_user_path(user), method: "delete"%>
	</div><br />

	<%end%>
</div>

app/views/layouts/_anonymous-nav-bar.html.erb
 <div class="topnav">
    <a href="/">Home</a>
    <a href="/login">Log In</a>
    <a href="/rewards">Rewards</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/pages/_anonymous-nav-bar.html.erb
<div class="topnav">
	<a href="/">Home</a>
	<a href="/login">Log In</a>
	<a href="/rewards">Rewards</a>
</div>
	

app/views/pages/_nav-bar.html.erb
<div class="topnav">
	<a href="/">Home</a>
	<a href="/login">Log In</a>
	<a href="/rewards">Rewards</a>
</div>
	

app/views/pages/main.html.erb
<%=render partial: "anonymous-nav-bar" %>

<div class="container">
  <h1>Welcome to Point Box </h1>

  <h2> New to Point Box? Sign up <%= link_to "Here", new_user_path %></h2>
</div>

app/views/pages/sign_up.html.erb
<%=render partial: "anonymous-nav-bar" %>

<h1>Sign Up</h1>

app/views/rewards/index.html.erb
<%=render partial: "users/user-nav-bar" %>
  <div class="container">
  <h1>Available Rewards:</h1>

  <% @rewards.each do |reward| %>
    <div class="boxed">
      <h3><%=reward.name%></h3>
      <p><%=reward.description%></p>
      <p><%=reward.price%> points</p>
      <p><%= link_to "Purchase", edit_reward_path(reward)%></p>
    </div>
    <% end %>
</div>

app/views/users/_user-nav-bar.html.erb
<div class="topnav">
    <%=link_to "Home", user_path(session[:user_id])%>
    <a href="/rewards">Rewards</a>
</div>

app/views/users/new.html.erb
<%=render partial: "pages/anonymous-nav-bar" %>

<div class="form">
    <%= form_for(@user) do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account"%>
    <% end %>
</div>

app/views/users/show.html.erb
<%=render partial: "user-nav-bar" %>
<div class="container">
  <div class="boxed">
    <h1>Welcome <%=@user.username%></h1>
      <p>Points available: <%=@user.available_points%></p>
      <p>Points spent: <%=@user.spent_points%></p>
  </div>

	<div class="items">
  <h1>Rewards: </h1>
    <%@user.rewards.each do |reward| %>
      <div class="boxed">
        <h3><%=reward.name%></h3>
        <p><%=reward.description%></p>
      </div>
    <%end%>
	</div>		
</div>